# Generated by Django 6.1 on 2026-08-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sale_credit_posted_at_sale_payment_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
