from django.urls import path
from django.contrib.auth.decorators import login_required, user_passes_test

from . import views


staff_required = user_passes_test(lambda user: user.is_authenticated and user.is_staff)


urlpatterns = [
    path("", login_required(views.dashboard), name="dashboard"),
    path("pos/", login_required(views.pos), name="pos"),
    path("pos/buscar/", login_required(views.pos_search), name="pos_search"),
    path("pos/agregar/<int:pk>/", login_required(views.pos_add_item), name="pos_add_item"),
    path("pos/actualizar/<int:pk>/", login_required(views.pos_update_item), name="pos_update_item"),
    path("pos/vaciar/", login_required(views.pos_clear_cart), name="pos_clear_cart"),
    path("pos/cobrar/", login_required(views.pos_checkout), name="pos_checkout"),
    path("ventas/", login_required(views.sales_overview), name="sales_overview"),
    path("ventas/listado/", login_required(views.sales_list), name="sales_list"),
    path("ventas/<int:pk>/", login_required(views.sale_detail), name="sale_detail"),
    path("ventas/<int:pk>/anular/", login_required(views.sale_cancel), name="sale_cancel"),
    path("ventas/devoluciones/", login_required(views.sales_returns), name="sales_returns"),
        path("ventas/devoluciones/nueva/", login_required(views.sale_return_create), name="sale_return_create"),
        path("ventas/devoluciones/<int:pk>/editar/", login_required(views.sale_return_edit), name="sale_return_edit"),
        path("ventas/devoluciones/<int:pk>/eliminar/", login_required(views.sale_return_delete), name="sale_return_delete"),
    path("inventario/", login_required(views.inventory_overview), name="inventory_overview"),
    path("inventario/productos/", login_required(views.products), name="products"),
    path("inventario/categorias/", login_required(views.categories), name="categories"),
    path("inventario/marcas/", login_required(views.brands), name="brands"),
    path("inventario/stock/", login_required(views.stock_by_branch), name="stock_by_branch"),
    path("inventario/kardex/", login_required(views.kardex), name="kardex"),
    path("inventario/ajustes/", login_required(views.inventory_adjustments), name="inventory_adjustments"),
    path("inventario/ajustes/nuevo/", login_required(views.inventory_adjustment_create), name="inventory_adjustment_create"),
    path("inventario/ajustes/<int:pk>/editar/", login_required(views.inventory_adjustment_edit), name="inventory_adjustment_edit"),
    path("inventario/ajustes/<int:pk>/eliminar/", login_required(views.inventory_adjustment_delete), name="inventory_adjustment_delete"),
    path("compras/", login_required(views.purchases_overview), name="purchases_overview"),
    path("compras/nueva/", login_required(views.purchase_create), name="new_purchase"),
    path("compras/proveedores/", login_required(views.suppliers), name="suppliers"),
    path("compras/listado/", login_required(views.purchases_list), name="purchases_list"),
    path("compras/<int:pk>/editar/", login_required(views.purchase_edit), name="purchase_edit"),
    path("compras/<int:pk>/eliminar/", login_required(views.purchase_delete), name="purchase_delete"),
    path("compras/nuevo/", login_required(views.purchase_create), name="purchase_create"),
    path("traspasos/", login_required(views.transfers_overview), name="transfers_overview"),
    path("traspasos/nuevo/", login_required(views.transfer_create), name="new_transfer"),
    path("traspasos/enviados/", login_required(views.sent_transfers), name="sent_transfers"),
    path("traspasos/recibidos/", login_required(views.received_transfers), name="received_transfers"),
    path("traspasos/pendientes/", login_required(views.pending_transfers), name="pending_transfers"),
    path("traspasos/listado/", login_required(views.transfers_list), name="transfers_list"),
    path("traspasos/<int:pk>/editar/", login_required(views.transfer_edit), name="transfer_edit"),
    path("traspasos/<int:pk>/eliminar/", login_required(views.transfer_delete), name="transfer_delete"),
    path("traspasos/nuevo/crear/", login_required(views.transfer_create), name="transfer_create"),
    path("clientes/", login_required(views.customers_overview), name="customers_overview"),
    path("clientes/creditos/", login_required(views.credits_overview), name="credits_overview"),
    path("clientes/cobros/", login_required(views.collections_overview), name="collections_overview"),
    path("caja/", login_required(views.cash_overview), name="cash_overview"),
    path("caja/mi-turno/", login_required(views.my_shift), name="my_shift"),
    path("caja/apertura/", login_required(views.cash_opening), name="cash_opening"),
    path("caja/movimientos/", login_required(views.cash_movements), name="cash_movements"),
    path("caja/gastos/", login_required(views.cash_expenses), name="cash_expenses"),
    path("caja/arqueo/", login_required(views.cash_close), name="cash_close"),
    path("reportes/", login_required(views.reports_overview), name="reports_overview"),
    path("sucursal/seleccionar/", login_required(views.set_selected_branch), name="set_selected_branch"),
    path("administracion/", staff_required(views.admin_overview), name="admin_overview"),
    path("administracion/sucursales/", staff_required(views.admin_branches), name="admin_branches"),
    path("administracion/usuarios/", staff_required(views.admin_users), name="admin_users"),
    path("administracion/usuarios/nuevo/", staff_required(views.admin_user_create), name="admin_user_create"),
    path("administracion/usuarios/<int:pk>/editar/", staff_required(views.admin_user_edit), name="admin_user_edit"),
    path("administracion/usuarios/<int:pk>/eliminar/", staff_required(views.admin_user_delete), name="admin_user_delete"),
    path("administracion/roles/", staff_required(views.admin_roles), name="admin_roles"),
    path("administracion/roles/nuevo/", staff_required(views.admin_role_create), name="admin_role_create"),
    path("administracion/roles/<int:pk>/editar/", staff_required(views.admin_role_edit), name="admin_role_edit"),
    path("administracion/roles/<int:pk>/eliminar/", staff_required(views.admin_role_delete), name="admin_role_delete"),
    path("administracion/configuracion/", staff_required(views.admin_settings), name="admin_settings"),
    path("catalogos/sucursales/", staff_required(login_required(views.branches)), name="branches"),
    path("catalogos/sucursales/nueva/", staff_required(login_required(views.branch_create)), name="branch_create"),
    path("catalogos/sucursales/<int:pk>/editar/", staff_required(login_required(views.branch_edit)), name="branch_edit"),
    path("catalogos/sucursales/<int:pk>/eliminar/", staff_required(login_required(views.branch_delete)), name="branch_delete"),
    path("catalogos/categorias/", login_required(views.categories_list), name="categories_list"),
    path("catalogos/categorias/nueva/", login_required(views.category_create), name="category_create"),
    path("catalogos/categorias/<int:pk>/editar/", login_required(views.category_edit), name="category_edit"),
    path("catalogos/categorias/<int:pk>/eliminar/", login_required(views.category_delete), name="category_delete"),
    path("catalogos/productos/", login_required(views.products_list), name="products_list"),
    path("catalogos/productos/nuevo/", login_required(views.product_create), name="product_create"),
    path("catalogos/productos/<int:pk>/editar/", login_required(views.product_edit), name="product_edit"),
    path("catalogos/productos/<int:pk>/eliminar/", login_required(views.product_delete), name="product_delete"),
    path("catalogos/marcas/", login_required(views.brands_list), name="brands_list"),
    path("catalogos/marcas/nueva/", login_required(views.brand_create), name="brand_create"),
    path("catalogos/marcas/<int:pk>/editar/", login_required(views.brand_edit), name="brand_edit"),
    path("catalogos/marcas/<int:pk>/eliminar/", login_required(views.brand_delete), name="brand_delete"),
    path("catalogos/proveedores/", login_required(views.suppliers_list), name="suppliers_list"),
    path("catalogos/proveedores/nuevo/", login_required(views.supplier_create), name="supplier_create"),
    path("catalogos/proveedores/<int:pk>/editar/", login_required(views.supplier_edit), name="supplier_edit"),
    path("catalogos/proveedores/<int:pk>/eliminar/", login_required(views.supplier_delete), name="supplier_delete"),
    path("catalogos/clientes/", login_required(views.customers_list), name="customers_list"),
    path("catalogos/clientes/nuevo/", login_required(views.customer_create), name="customer_create"),
    path("catalogos/clientes/<int:pk>/editar/", login_required(views.customer_edit), name="customer_edit"),
    path("catalogos/clientes/<int:pk>/eliminar/", login_required(views.customer_delete), name="customer_delete"),
]
